#!/bin/bash

case "$1" in
    n)
        input=`showconsolefont -i`
        IFS='x'
        read -r RW CW CNT <<< "$input"
        setfont ter-v${CW}${i}n -m 8859-5
        ;;
    
    b)
        input=`showconsolefont -i`
        IFS='x'
        read -r RW CW CNT <<< "$input"
        setfont ter-v${CW}${i}b -m 8859-5
        ;;
    
    +)
        input=`showconsolefont -i`
        IFS='x'
        read -r RW CW CNT <<< "$input"
        case "$CW" in
            12)
                setfont ter-v14b -m 8859-5
                ;;
            
            14)
                setfont ter-v16b -m 8859-5
                ;;
            
            16)
                setfont ter-v18b -m 8859-5
                ;;

            18)
                setfont ter-v20b -m 8859-5
                ;;

            20)
                setfont ter-v22b -m 8859-5
                ;;

            22)
                setfont ter-v24b -m 8859-5
                ;;
            24)
                setfont ter-v28b -m 8859-5
                ;;
            
            28)
                setfont ter-v32b -m 8859-5
                ;;
        esac
        ;;
        
    -)
        input=`showconsolefont -i`
        IFS='x'
        read -r RW CW CNT <<< "$input"
        case "$CW" in
            14)
                setfont ter-v12n -m 8859-5
                ;;
            
            16)
                setfont ter-v14b -m 8859-5
                ;;
            
            18)
                setfont ter-v16b -m 8859-5
                ;;

            20)
                setfont ter-v18b -m 8859-5
                ;;

            22)
                setfont ter-v20b -m 8859-5
                ;;

            24)
                setfont ter-v22b -m 8859-5
                ;;
            28)
                setfont ter-v24b -m 8859-5
                ;;
            
            32)
                setfont ter-v28b -m 8859-5
                ;;
            
        esac
        ;;
    
    12n)
        setfont ter-v${1} -m 8859-5
        ;;
    
    14b)
        setfont ter-v${1} -m 8859-5
        ;;
    
    14n)
        setfont ter-v${1} -m 8859-5
        ;;
    16b)
        setfont ter-v${1} -m 8859-5
        ;;
    16n)
        setfont ter-v${1} -m 8859-5
        ;;
    18b)
        setfont ter-v${1} -m 8859-5
        ;;
    18n)
        setfont ter-v${1} -m 8859-5
        ;;
    20b)
        setfont ter-v${1} -m 8859-5
        ;;
    20n)
        setfont ter-v${1} -m 8859-5
        ;;
    22b)
        setfont ter-v${1} -m 8859-5
        ;;
    22n)
        setfont ter-v${1} -m 8859-5
        ;;
    24b)
        setfont ter-v${1} -m 8859-5
        ;;
    24n)
        setfont ter-v${1} -m 8859-5
        ;;
    28b)
        setfont ter-v${1} -m 8859-5
        ;;
    28n)
        setfont ter-v${1} -m 8859-5
        ;;
    32b)
        setfont ter-v${1} -m 8859-5
        ;;
    32n)
        setfont ter-v${1} -m 8859-5
        ;;
    *)
        echo "Usage for biger|smaller font: $0 {+|-}" 
        echo "Usage for thin|bold font    : $0 {n|b}"
        echo "Usage                       : $0 {12n|14b|14n|16b|16n|18b|18n|20b|20n|22b|22n|24b|24n|28b|28n|32b|32n}" 
        exit 1
esac

showconsolefont -i
